spring:
  application:
    name: Quizz
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/quiz_app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/quizdev/protocol/openid-connect/certs
server:
  port: 8080
